CREATE TABLE "opentamago_connect_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_connect_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"peerId" varchar(64) NOT NULL,
	"characterName" varchar(255) NOT NULL,
	"characterAvatar" text,
	"isHost" boolean DEFAULT false,
	"joinedAt" timestamp with time zone NOT NULL,
	"leftAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "opentamago_connect_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_connect_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shortSlug" varchar(8) NOT NULL,
	"longSlug" varchar(128) NOT NULL,
	"hostPeerId" varchar(64) NOT NULL,
	"hostUserId" varchar(255),
	"maxParticipants" integer DEFAULT 8,
	"isPublic" boolean DEFAULT false,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"lastActivityAt" timestamp with time zone NOT NULL,
	CONSTRAINT "opentamago_connect_session_shortSlug_unique" UNIQUE("shortSlug"),
	CONSTRAINT "opentamago_connect_session_longSlug_unique" UNIQUE("longSlug")
);
--> statement-breakpoint
ALTER TABLE "opentamago_connect_participant" ADD CONSTRAINT "opentamago_connect_participant_sessionId_opentamago_connect_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."opentamago_connect_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_connect_session" ADD CONSTRAINT "opentamago_connect_session_hostUserId_opentamago_user_id_fk" FOREIGN KEY ("hostUserId") REFERENCES "public"."opentamago_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "connect_participant_session_idx" ON "opentamago_connect_participant" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "connect_short_slug_idx" ON "opentamago_connect_session" USING btree ("shortSlug");--> statement-breakpoint
CREATE INDEX "connect_long_slug_idx" ON "opentamago_connect_session" USING btree ("longSlug");--> statement-breakpoint
CREATE INDEX "connect_expires_at_idx" ON "opentamago_connect_session" USING btree ("expiresAt");