CREATE TABLE "opentamago_connect_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_connect_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"peerId" varchar(64) NOT NULL,
	"characterName" varchar(255) NOT NULL,
	"characterAvatar" text,
	"isHost" boolean DEFAULT false,
	"joinedAt" timestamp with time zone NOT NULL,
	"leftAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "opentamago_connect_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_connect_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shortSlug" varchar(8) NOT NULL,
	"longSlug" varchar(128) NOT NULL,
	"hostPeerId" varchar(64) NOT NULL,
	"hostUserId" uuid,
	"passwordHash" varchar(128),
	"maxParticipants" integer DEFAULT 8,
	"isPublic" boolean DEFAULT false,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"lastActivityAt" timestamp with time zone NOT NULL,
	CONSTRAINT "opentamago_connect_session_shortSlug_unique" UNIQUE("shortSlug"),
	CONSTRAINT "opentamago_connect_session_longSlug_unique" UNIQUE("longSlug")
);
--> statement-breakpoint
CREATE TABLE "opentamago_feedback" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid NOT NULL,
	"feedbackType" varchar(32) NOT NULL,
	"message" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "opentamago_file_share_channel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_file_share_channel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shortSlug" varchar(8) NOT NULL,
	"longSlug" varchar(128) NOT NULL,
	"secret" uuid NOT NULL,
	"uploaderPeerId" varchar(64) NOT NULL,
	"userId" uuid,
	"fileName" varchar(255),
	"fileSize" bigint DEFAULT 0,
	"hasPassword" boolean DEFAULT false,
	"passwordHash" varchar(255),
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"lastRenewedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "opentamago_file_share_channel_shortSlug_unique" UNIQUE("shortSlug"),
	CONSTRAINT "opentamago_file_share_channel_longSlug_unique" UNIQUE("longSlug")
);
--> statement-breakpoint
CREATE TABLE "opentamago_account" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" uuid NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"password" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "opentamago_session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" uuid NOT NULL,
	CONSTRAINT "opentamago_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "opentamago_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean NOT NULL,
	"image" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "opentamago_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "opentamago_verification" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp
);
--> statement-breakpoint
ALTER TABLE "opentamago_connect_participant" ADD CONSTRAINT "opentamago_connect_participant_sessionId_opentamago_connect_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."opentamago_connect_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_connect_session" ADD CONSTRAINT "opentamago_connect_session_hostUserId_opentamago_user_id_fk" FOREIGN KEY ("hostUserId") REFERENCES "public"."opentamago_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_feedback" ADD CONSTRAINT "opentamago_feedback_userId_opentamago_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."opentamago_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_file_share_channel" ADD CONSTRAINT "opentamago_file_share_channel_userId_opentamago_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."opentamago_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_account" ADD CONSTRAINT "opentamago_account_userId_opentamago_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."opentamago_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opentamago_session" ADD CONSTRAINT "opentamago_session_userId_opentamago_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."opentamago_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "connect_participant_session_idx" ON "opentamago_connect_participant" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "connect_short_slug_idx" ON "opentamago_connect_session" USING btree ("shortSlug");--> statement-breakpoint
CREATE INDEX "connect_long_slug_idx" ON "opentamago_connect_session" USING btree ("longSlug");--> statement-breakpoint
CREATE INDEX "connect_expires_at_idx" ON "opentamago_connect_session" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "file_share_short_slug_idx" ON "opentamago_file_share_channel" USING btree ("shortSlug");--> statement-breakpoint
CREATE INDEX "file_share_long_slug_idx" ON "opentamago_file_share_channel" USING btree ("longSlug");--> statement-breakpoint
CREATE INDEX "file_share_expires_at_idx" ON "opentamago_file_share_channel" USING btree ("expiresAt");