CREATE TABLE "opentamago_file_share_channel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opentamago_file_share_channel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shortSlug" varchar(8) NOT NULL,
	"longSlug" varchar(128) NOT NULL,
	"secret" uuid NOT NULL,
	"uploaderPeerId" varchar(64) NOT NULL,
	"userId" varchar(255),
	"fileName" varchar(255),
	"fileSize" bigint DEFAULT 0,
	"hasPassword" boolean DEFAULT false,
	"passwordHash" varchar(255),
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"lastRenewedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "opentamago_file_share_channel_shortSlug_unique" UNIQUE("shortSlug"),
	CONSTRAINT "opentamago_file_share_channel_longSlug_unique" UNIQUE("longSlug")
);
--> statement-breakpoint
ALTER TABLE "opentamago_file_share_channel" ADD CONSTRAINT "opentamago_file_share_channel_userId_opentamago_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."opentamago_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "file_share_short_slug_idx" ON "opentamago_file_share_channel" USING btree ("shortSlug");--> statement-breakpoint
CREATE INDEX "file_share_long_slug_idx" ON "opentamago_file_share_channel" USING btree ("longSlug");--> statement-breakpoint
CREATE INDEX "file_share_expires_at_idx" ON "opentamago_file_share_channel" USING btree ("expiresAt");